//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyConfiguratorApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurveyConfiguratorApp.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, Ask the Admin for help.
        /// </summary>
        internal static string DB_FAILED_NERORK_CONNECTION {
            get {
                return ResourceManager.GetString("DB_FAILED_NERORK_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Question does not exists.
        /// </summary>
        internal static string DB_RECORD_NOT_EXISTS {
            get {
                return ResourceManager.GetString("DB_RECORD_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this question?.
        /// </summary>
        internal static string DELETE_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faces.
        /// </summary>
        internal static string FACES {
            get {
                return ResourceManager.GetString("FACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        internal static string LABEL_STATUS {
            get {
                return ResourceManager.GetString("LABEL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed, do you still want to save it?.
        /// </summary>
        internal static string SAVE_CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("SAVE_CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failed.
        /// </summary>
        internal static string SAVE_FAILED {
            get {
                return ResourceManager.GetString("SAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Successful.
        /// </summary>
        internal static string SAVE_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("SAVE_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        internal static string SLIDER {
            get {
                return ResourceManager.GetString("SLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        internal static string STARS {
            get {
                return ResourceManager.GetString("STARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected Successfully.
        /// </summary>
        internal static string TEST_CONNECTION {
            get {
                return ResourceManager.GetString("TEST_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        internal static string TEST_CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("TEST_CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation errors, Please check the inputs.
        /// </summary>
        internal static string VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very long question text.
        /// </summary>
        internal static string VALIDATION_ERROR_LONG_TEXT {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_LONG_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Should be unique.
        /// </summary>
        internal static string VALIDATION_ERROR_ORDER_EXIST {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_ORDER_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text Required.
        /// </summary>
        internal static string VALIDATION_ERROR_QUESTION_TEXT {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_QUESTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very short question text.
        /// </summary>
        internal static string VALIDATION_ERROR_SHORT_TEXT {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_SHORT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption Text Required.
        /// </summary>
        internal static string VALIDATION_ERROR_SLIDER_CAPTION {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_SLIDER_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Value Should be less than Max Value.
        /// </summary>
        internal static string VALIDATION_ERROR_SLIDER_VALUE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_SLIDER_VALUE", resourceCulture);
            }
        }
    }
}
